data:
  tickers:
    - "PETR4.SA"
    - "VALE3.SA"
    - "BBDC4.SA"
    - "ITUB4.SA"
    - "BBAS3.SA"
    - "B3SA3.SA"
    - "ABEV3.SA"
    - "VIVT3.SA"
  start_date: "2017-01-01"
  end_date: "2025-08-18"
  
  raw_data_path: "data/01_raw/"
  features_data_path: "data/03_features/"

features:
  indicators:
    ema_short: 21
    ema_long: 50
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
    rsi_length: 14
    bbands_length: 20
    bbands_std: 2.0
    adx_length: 14
    atr_length: 14
    mfi_length: 14
    stoch_length: 14

  wavelet:
    family: 'db8'
    level: 1

model_training:
  train_final_date: "2022-12-31"
  validation_start_date: "2023-01-01"
  validation_end_date: "2023-12-31"
  test_start_date: "2024-01-01"
  test_end_date: "2025-01-01"
  target_column: "target"
  
  # Parâmetros do Triple Barrier Method
  triple_barrier:
    holding_days: 7
    profit_multiplier: 2.0
    loss_multiplier: 1.5     

  xgboost_params:
    objective: "multi:softprob"
    'num_class': 3
    eval_metric: "mlogloss"
    n_estimators: 1000
    learning_rate: 0.05
    max_depth: 5
    early_stopping_rounds: 50

  model_output_path: "models/01_xgboost/"

backtesting:
  initial_capital: 100000.0
  transaction_cost_pct: 0.001
  
  # Parâmetros realistas adicionais
  lot_size: 100               # Lotes de 100 ações (padrão B3)
  use_real_cdi: true          # Usar CDI real do arquivo cdi_daily.csv
  cash_daily_rate: 0.0004     # Taxa fixa de fallback se CDI real não disponível
  
  # Configuração de slippage dinâmico
  slippage_config:
    base_bps: 0.2             # Slippage base (0.2 bps)
    min_bps: 0.1              # Slippage mínimo (0.1 bps)
    max_bps: 2.0              # Slippage máximo (2.0 bps)
    volume_factor: 0.5        # Fator de impacto do volume
    volatility_factor: 1.0    # Fator de impacto da volatilidade
    size_factor: 0.3          # Fator de impacto do tamanho da ordem

  initial_simulation_date: "2024-01-01"
  final_simulation_date: "2025-01-01"

  results_path: "reports"
  
  threshold_optimization:
    enabled: true  # Ativar otimização de threshold
    metric: "sharpe"  # Métrica principal para otimização financeira
    min_threshold: 0.5  # Threshold mínimo (legado)
    max_threshold: 0.6  # Threshold máximo (legado)
    hold_min_days: 3    # Histerese: mínimo de dias entre trocas de estado

  position_sizing:
    enabled: true
    min_fraction: 0.2   # fração mínima do capital quando comprado
    max_fraction: 1.0   # fração máxima do capital quando comprado
    method: "sigmoid"    # métodos disponíveis: linear, sigmoid, step, quadratic