data:
  tickers:
    - "PETR4.SA"
    - "VALE3.SA"
    - "BBDC4.SA"
    - "ITUB4.SA"
    - "BBAS3.SA"
    - "B3SA3.SA"
    - "ABEV3.SA"
    - "VIVT3.SA"
  start_date: "2017-01-01"
  end_date: "2025-08-18"
  
  raw_data_path: "data/01_raw/"
  features_data_path: "data/03_features/"

features:
  indicators:
    ema_short: 21
    ema_long: 50
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
    rsi_length: 14
    bbands_length: 20
    bbands_std: 2.0
    adx_length: 14
    atr_length: 14
    mfi_length: 14
    stoch_length: 14

  wavelet:
    family: 'db8'
    level: 1

model_training:
  train_final_date: "2022-12-31"
  validation_start_date: "2023-01-01"
  validation_end_date: "2023-12-31"
  test_start_date: "2024-01-01"
  test_end_date: "2025-01-01"
  target_column: "target"

  xgboost_params:
    objective: "binary:logistic"
    eval_metric: "logloss"
    n_estimators: 1000
    learning_rate: 0.05
    max_depth: 5
    early_stopping_rounds: 50

  model_output_path: "models/01_xgboost/"

backtesting:
  initial_capital: 100000.0
  transaction_cost_pct: 0.001

  initial_simulation_date: "2024-01-01"
  final_simulation_date: "2025-01-01"

  results_path: "reports"
  
  threshold_optimization:
    enabled: true  # Ativar otimização de threshold
    metric: "sharpe"  # Métrica principal para otimização financeira
    min_threshold: 0.5  # Threshold mínimo (legado)
    max_threshold: 0.6  # Threshold máximo (legado)
    hold_min_days: 3    # Histerese: mínimo de dias entre trocas de estado

  position_sizing:
    enabled: true
    min_fraction: 0.2   # fração mínima do capital quando comprado
    max_fraction: 1.0   # fração máxima do capital quando comprado
    method: "prob_linear"  # mapeia probabilidade -> fração de posição